name: First Workflow
on:
    push:
        branches: ["main"]

jobs:
    run-shell-commands:
        runs-on: ubuntu-latest
        steps:
            - name: Print String
              run: echo "Hello World"
            - name: Multiline commands
              run: |
                node -v
                npm -v
    dependent-job:
        runs-on: windows-latest
        needs: run-shell-commands
        steps:
            - name: echo a string
              run: Write-Output "Windows String"