name: WorkFlow Commands
on:
    push:
        branches: ["main"]
jobs:
    workflow-commands:
        runs-on: ubuntu-latest
        steps:
            - name: Group of logs
              run: |
                echo "::group:: Series of Statement"
                echo "Message-1"
                echo "Message-2"
                echo "Message-3"
                echo "::endgroup::"
            - name: Masking a Value
              run: echo "::add-mask::Password"
            - name: Log Error
              run: echo "::error::missing colon"